# QCA IPQ4019 Sound Card Support
snd-soc-ipq4019-objs := ipq4019.o
snd-soc-ipq4019-cpu-dai-objs := ipq4019-cpu-dai.o
snd-soc-ipq4019-pcm-i2s-objs := ipq4019-pcm-i2s.o
snd-soc-ipq4019-pcm-tdm-objs := ipq4019-pcm-tdm.o
snd-soc-ipq4019-pcm-spdif-objs := ipq4019-pcm-spdif.o

obj-$(CONFIG_SND_SOC_IPQ4019) += ipq4019.o
obj-$(CONFIG_SND_SOC_IPQ4019_ADSS) += ipq4019-adss.o
obj-$(CONFIG_SND_SOC_IPQ4019_CPU_DAI) += snd-soc-ipq4019-cpu-dai.o
obj-$(CONFIG_SND_SOC_IPQ4019_STEREO) += ipq4019-stereo.o
obj-$(CONFIG_SND_SOC_IPQ4019_MBOX) += ipq4019-mbox.o
obj-$(CONFIG_SND_SOC_IPQ4019_PCM_I2S) += snd-soc-ipq4019-pcm-i2s.o
obj-$(CONFIG_SND_SOC_IPQ4019_CODEC) += ipq4019-codec.o
obj-$(CONFIG_SND_SOC_IPQ4019_PCM_SPDIF) += snd-soc-ipq4019-pcm-spdif.o
obj-$(CONFIG_SND_SOC_IPQ4019_PCM_TDM) += snd-soc-ipq4019-pcm-tdm.o
