# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the Microchip phy drivers.
#

obj-$(CONFIG_PHY_MICROCHIP_SAMA7_USB)	+= phy-sama7-utmi-clk.o phy-sama7-usb.o
obj-$(CONFIG_PHY_SPARX5_SERDES) := sparx5_serdes.o
