# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_VIDEO_MCHP_DSCMI) += mchp-dscmi.o
obj-$(CONFIG_VIDEO_MICROCHIP_COMMON) += microchip-common.o
obj-$(CONFIG_VIDEO_MICROCHIP_MIPI_CSI2) += microchip-mipi-csi2rx.o
obj-$(CONFIG_VIDEO_MICROCHIP_VIDEO_CAPTURE) += microchip-vcpp.o

