/*
 * Copyright 2024-2025 Morse Micro
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 * Autogenerated file - do not hand edit
 */

#include "reg_rules.h"
#include "channel_alphas.h"

#define _MRR MORSE_REG_RULE
#define _MRR_KHZ MORSE_REG_RULE_KHZ

struct morse_reg_rule au_2020_reg_rules[] = {
	/* S1G Actual Frequencies */
	_MRR(915, 916, 1, 0, 30, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR(916, 920, 4, 0, 30, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR(920, 928, 8, 0, 30, AUTO_BW, 10000, 10000, false, 0, 0, 0),

	/* S1G->11ac Mapped Frequencies */
	_MRR(5550, 5570,  20, 0, 30, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR(5570, 5650,  80, 0, 30, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR(5735, 5895, 160, 0, 30, AUTO_BW, 10000, 10000, false, 0, 0, 0),
};

static struct morse_regdomain mors_au_2020_regdom = {
	.n_reg_rules = ARRAY_SIZE(au_2020_reg_rules),
	.alpha2 = CHANNEL_ALPHA_AU,
	.reg_rules = au_2020_reg_rules,
	.channelization_scheme = CHANNELIZATION_SCHEME_IEEE80211_2020
};

struct morse_reg_rule au_reg_rules[] = {
	/* S1G Actual Frequencies */
	_MRR_KHZ(915500, 923500, 8000, 0, 30, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR_KHZ(917500, 925500, 8000, 0, 30, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR_KHZ(919500, 927500, 8000, 0, 30, AUTO_BW, 10000, 10000, false, 0, 0, 0),

	/* S1G->11ac Mapped Frequencies */
	_MRR(5170, 5330, 160, 0, 30, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR(5735, 5895, 160, 0, 30, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR(5490, 5650, 160, 0, 30, AUTO_BW, 10000, 10000, false, 0, 0, 0),
};

static struct morse_regdomain mors_au_regdom = {
	.n_reg_rules = ARRAY_SIZE(au_reg_rules),
	.alpha2 = CHANNEL_ALPHA_AU,
	.reg_rules = au_reg_rules,
	.channelization_scheme = CHANNELIZATION_SCHEME_IEEE80211_REVMF
};

struct morse_reg_rule au_2024_reg_rules[] = {
	/* S1G Actual Frequencies */
	_MRR_KHZ(915500, 923500, 8000, 0, 30, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR_KHZ(919500, 927500, 8000, 0, 30, AUTO_BW, 10000, 10000, false, 0, 0, 0),

	/* S1G->11ac Mapped Frequencies */
	_MRR(5170, 5330, 160, 0, 30, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR(5490, 5650, 160, 0, 30, AUTO_BW, 10000, 10000, false, 0, 0, 0),
};

static struct morse_regdomain mors_au_2024_regdom = {
	.n_reg_rules = ARRAY_SIZE(au_2024_reg_rules),
	.alpha2 = CHANNEL_ALPHA_AU,
	.reg_rules = au_2024_reg_rules,
	.channelization_scheme = CHANNELIZATION_SCHEME_IEEE80211_2024
};

struct morse_reg_rule br_reg_rules[] = {
	/* S1G Actual Frequencies */
	_MRR(906, 907, 1, 0, 36, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR(915, 916, 1, 0, 36, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR(902, 904, 2, 0, 36, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR(904, 906, 2, 0, 36, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR(916, 920, 4, 0, 36, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR(920, 928, 8, 0, 36, AUTO_BW, 10000, 10000, false, 0, 0, 0),

	/* S1G->11ac Mapped Frequencies */
	_MRR(5210, 5230,  20, 0, 36, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR(5550, 5570,  20, 0, 36, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR(5650, 5690,  40, 0, 36, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR(5170, 5210,  40, 0, 36, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR(5570, 5650,  80, 0, 36, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR(5735, 5895, 160, 0, 36, AUTO_BW, 10000, 10000, false, 0, 0, 0),
};

static struct morse_regdomain mors_br_regdom = {
	.n_reg_rules = ARRAY_SIZE(br_reg_rules),
	.alpha2 = CHANNEL_ALPHA_BR,
	.reg_rules = br_reg_rules,
	.channelization_scheme = CHANNELIZATION_SCHEME_NONE
};

struct morse_reg_rule ca_reg_rules[] = {
	/* S1G Actual Frequencies */
	_MRR(902, 904, 2, 0, 36, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR(904, 912, 8, 0, 36, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR(912, 920, 8, 0, 36, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR(920, 928, 8, 0, 36, AUTO_BW, 10000, 10000, false, 0, 0, 0),

	/* S1G->11ac Mapped Frequencies */
	_MRR(5650, 5690,  40, 0, 36, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR(5170, 5330, 160, 0, 36, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR(5490, 5650, 160, 0, 36, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR(5735, 5895, 160, 0, 36, AUTO_BW, 10000, 10000, false, 0, 0, 0),
};

static struct morse_regdomain mors_ca_regdom = {
	.n_reg_rules = ARRAY_SIZE(ca_reg_rules),
	.alpha2 = CHANNEL_ALPHA_CA,
	.reg_rules = ca_reg_rules,
	.channelization_scheme = CHANNELIZATION_SCHEME_NONE
};

struct morse_reg_rule eu_reg_rules[] = {
	/* S1G Actual Frequencies */
	_MRR(867, 868, 1, 0, 16, AUTO_BW,  1000,   280, false, 0, 0, 0),
	_MRR(863, 865, 2, 0, 16, AUTO_BW,  1000,   280, false, 0, 0, 0),
	_MRR(865, 867, 2, 0, 16, AUTO_BW,  1000,   280, false, 0, 0, 0),

	/* S1G->11ac Mapped Frequencies */
	_MRR(5210, 5230,  20, 0, 16, AUTO_BW,  1000,   280, false, 0, 0, 0),
	_MRR(5650, 5690,  40, 0, 16, AUTO_BW,  1000,   280, false, 0, 0, 0),
	_MRR(5170, 5210,  40, 0, 16, AUTO_BW,  1000,   280, false, 0, 0, 0),
};

static struct morse_regdomain mors_eu_regdom = {
	.n_reg_rules = ARRAY_SIZE(eu_reg_rules),
	.alpha2 = CHANNEL_ALPHA_EU,
	.reg_rules = eu_reg_rules,
	.channelization_scheme = CHANNELIZATION_SCHEME_NONE
};

struct morse_reg_rule gb_reg_rules[] = {
	/* S1G Actual Frequencies */
	_MRR(867, 868, 1, 0, 16, AUTO_BW,  1000,   280, false, 0, 0, 0),
	_MRR_KHZ(917400, 919400, 1000, 0, 16, AUTO_BW,  1000,   280, false, 0, 0, 0),
	_MRR(863, 865, 2, 0, 16, AUTO_BW,  1000,   280, false, 0, 0, 0),
	_MRR(865, 867, 2, 0, 16, AUTO_BW,  1000,   280, false, 0, 0, 0),

	/* S1G->11ac Mapped Frequencies */
	_MRR(5210, 5230,  20, 0, 16, AUTO_BW,  1000,   280, false, 0, 0, 0),
	_MRR(5610, 5650,  20, 0, 16, AUTO_BW,  1000,   280, false, 0, 0, 0),
	_MRR(5650, 5690,  40, 0, 16, AUTO_BW,  1000,   280, false, 0, 0, 0),
	_MRR(5170, 5210,  40, 0, 16, AUTO_BW,  1000,   280, false, 0, 0, 0),
};

static struct morse_regdomain mors_gb_regdom = {
	.n_reg_rules = ARRAY_SIZE(gb_reg_rules),
	.alpha2 = CHANNEL_ALPHA_GB,
	.reg_rules = gb_reg_rules,
	.channelization_scheme = CHANNELIZATION_SCHEME_NONE
};

struct morse_reg_rule in_reg_rules[] = {
	/* S1G Actual Frequencies */
	_MRR(865, 868, 1, 0, 16, AUTO_BW,  1000,   280, false, 0, 0, 0),

	/* S1G->11ac Mapped Frequencies */
	_MRR(5170, 5230,  20, 0, 16, AUTO_BW,  1000,   280, false, 0, 0, 0),
};

static struct morse_regdomain mors_in_regdom = {
	.n_reg_rules = ARRAY_SIZE(in_reg_rules),
	.alpha2 = CHANNEL_ALPHA_IN,
	.reg_rules = in_reg_rules,
	.channelization_scheme = CHANNELIZATION_SCHEME_NONE
};

struct morse_reg_rule jp_reg_rules[] = {
	/* S1G Actual Frequencies */
	_MRR_KHZ(920500, 921500, 1000, 0, 16, AUTO_BW,  1000,  1000, true, 2000, 100000, 2000),
	_MRR_KHZ(922500, 926500, 4000, 0, 16, AUTO_BW,  1000,  1000, true, 2000, 100000, 2000),
	_MRR_KHZ(923500, 927500, 4000, 0, 16, AUTO_BW,  1000,  1000, true, 2000, 100000, 2000),

	/* S1G->11ac Mapped Frequencies */
	_MRR(5530, 5550,  20, 0, 16, AUTO_BW,  1000,  1000, true, 2000, 100000, 2000),
	_MRR(5170, 5250,  80, 0, 16, AUTO_BW,  1000,  1000, true, 2000, 100000, 2000),
	_MRR(5250, 5330,  80, 0, 16, AUTO_BW,  1000,  1000, true, 2000, 100000, 2000),
};

static struct morse_regdomain mors_jp_regdom = {
	.n_reg_rules = ARRAY_SIZE(jp_reg_rules),
	.alpha2 = CHANNEL_ALPHA_JP,
	.reg_rules = jp_reg_rules,
	.channelization_scheme = CHANNELIZATION_SCHEME_NONE
};

struct morse_reg_rule kr_reg_rules[] = {
	/* S1G Actual Frequencies */
	_MRR(926, 927, 1, 0, 17, AUTO_BW, 10000, 10000, false, 0, 220000, 264),
	_MRR_KHZ(917500, 919500, 2000, 0,  4, AUTO_BW, 10000, 10000, false, 0, 4000000, 50000),
	_MRR_KHZ(921500, 923500, 2000, 0, 10, AUTO_BW, 10000, 10000, false, 0, 4000000, 50000),
	_MRR(926, 930, 2, 0, 20, AUTO_BW, 10000, 10000, false, 0, 220000, 264),
	_MRR_KHZ(919500, 923500, 4000, 0,  4, AUTO_BW, 10000, 10000, false, 0, 4000000, 50000),

	/* S1G->11ac Mapped Frequencies */
	_MRR(5815, 5835,  20, 0, 17, AUTO_BW, 10000, 10000, false, 0, 220000, 264),
	_MRR(5650, 5690,  40, 0,  4, AUTO_BW, 10000, 10000, false, 0, 4000000, 50000),
	_MRR(5210, 5250,  40, 0, 10, AUTO_BW, 10000, 10000, false, 0, 4000000, 50000),
	_MRR(5815, 5895,  40, 0, 20, AUTO_BW, 10000, 10000, false, 0, 220000, 264),
	_MRR(5170, 5250,  80, 0,  4, AUTO_BW, 10000, 10000, false, 0, 4000000, 50000),
};

static struct morse_regdomain mors_kr_regdom = {
	.n_reg_rules = ARRAY_SIZE(kr_reg_rules),
	.alpha2 = CHANNEL_ALPHA_KR,
	.reg_rules = kr_reg_rules,
	.channelization_scheme = CHANNELIZATION_SCHEME_NONE
};

struct morse_reg_rule nz_reg_rules[] = {
	/* S1G Actual Frequencies */
	_MRR(915, 916, 1, 0, 30, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR(916, 920, 4, 0, 30, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR(920, 928, 8, 0, 36, AUTO_BW, 10000, 10000, false, 0, 0, 0),

	/* S1G->11ac Mapped Frequencies */
	_MRR(5550, 5570,  20, 0, 30, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR(5570, 5650,  80, 0, 30, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR(5735, 5895, 160, 0, 36, AUTO_BW, 10000, 10000, false, 0, 0, 0),
};

static struct morse_regdomain mors_nz_regdom = {
	.n_reg_rules = ARRAY_SIZE(nz_reg_rules),
	.alpha2 = CHANNEL_ALPHA_NZ,
	.reg_rules = nz_reg_rules,
	.channelization_scheme = CHANNELIZATION_SCHEME_NONE
};

struct morse_reg_rule sg_reg_rules[] = {
	/* S1G Actual Frequencies */
	_MRR(866, 869, 2, 0, 29, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR(920, 925, 4, 0, 22, AUTO_BW, 10000, 10000, false, 0, 0, 0),

	/* S1G->11ac Mapped Frequencies */
	_MRR(5190, 5210, 20, 0, 29, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR(5210, 5250, 40, 0, 29, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR(5735, 5815, 80, 0, 22, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR(5815, 5835, 20, 0, 22, AUTO_BW, 10000, 10000, false, 0, 0, 0),
};

static struct morse_regdomain mors_sg_regdom = {
	.n_reg_rules = ARRAY_SIZE(sg_reg_rules),
	.alpha2 = CHANNEL_ALPHA_SG,
	.reg_rules = sg_reg_rules,
	.channelization_scheme = CHANNELIZATION_SCHEME_NONE
};

struct morse_reg_rule us_reg_rules[] = {
	/* S1G Actual Frequencies */
	_MRR(902, 904, 2, 0, 36, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR(904, 912, 8, 0, 36, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR(912, 920, 8, 0, 36, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR(920, 928, 8, 0, 36, AUTO_BW, 10000, 10000, false, 0, 0, 0),

	/* S1G->11ac Mapped Frequencies */
	_MRR(5650, 5690,  40, 0, 36, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR(5170, 5330, 160, 0, 36, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR(5490, 5650, 160, 0, 36, AUTO_BW, 10000, 10000, false, 0, 0, 0),
	_MRR(5735, 5895, 160, 0, 36, AUTO_BW, 10000, 10000, false, 0, 0, 0),
};

static struct morse_regdomain mors_us_regdom = {
	.n_reg_rules = ARRAY_SIZE(us_reg_rules),
	.alpha2 = CHANNEL_ALPHA_US,
	.reg_rules = us_reg_rules,
	.channelization_scheme = CHANNELIZATION_SCHEME_NONE
};

static struct morse_regdomain *mors_regions[] = {
	&mors_au_2020_regdom,
	&mors_au_regdom,
	&mors_au_2024_regdom,
	&mors_br_regdom,
	&mors_ca_regdom,
	&mors_eu_regdom,
	&mors_gb_regdom,
	&mors_in_regdom,
	&mors_jp_regdom,
	&mors_kr_regdom,
	&mors_nz_regdom,
	&mors_sg_regdom,
	&mors_us_regdom,
};

/* Countries with multiple channelization */
const char *mors_multi_channelization_countries[] = {
	CHANNEL_ALPHA_AU,
};

bool morse_dot11ah_is_multi_channelization_country(const char *alpha)
{
	size_t i;

	for (i = 0; i < ARRAY_SIZE(mors_multi_channelization_countries); i++) {
		const char *cc = mors_multi_channelization_countries[i];

		if (!strncmp(cc, alpha, 2))
			return true;
	}
	return false;
}

const struct morse_regdomain *morse_reg_alpha_lookup(const char *alpha, u32 channelization_scheme)
{
	int i;

	if (!alpha)
		return NULL;

	for (i = 0; i < ARRAY_SIZE(mors_regions); i++) {
		const struct morse_regdomain *regdom = mors_regions[i];

		if (strncmp(regdom->alpha2, alpha, strlen(alpha)))
			continue;

		/*
		 * Enforce channelization scheme only for countries that have
		 * multiple channelization. For all others, ignore the
		 * scheme and return the first alpha match.
		 */
		if (morse_dot11ah_is_multi_channelization_country(alpha) &&
		    regdom->channelization_scheme != channelization_scheme)
			continue;

		return regdom;
	}
	return NULL;
}
